# Generated by Django 5.2.1 on 2025-05-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('direccion', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('telefono', models.CharField(max_length=20)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='hoteles/')),
            ],
        ),
    ]
